// epic-nfts/react-app/src/App.jsx
import './styles/App.css';
import twitterLogo from './assets/twitter-logo.svg';
import { ethers } from "ethers";
import React, { useEffect, useState } from "react";
import myEpicNft from './utils/MyEpicNFT.json';

const TWITTER_HANDLE = '_buildspace';
const TWITTER_LINK = `https://twitter.com/${TWITTER_HANDLE}`;
const OPENSEA_LINK = '';
const TOTAL_MINT_COUNT = 50;

// I moved the contract address to the top for easy access.
const CONTRACT_ADDRESS = "0xbFa93c1D67288bE69ff0Ce8AD04A0728015e8294";

const App = () => {
    
    const [minting, setMinting] = useState(false);
    const [currentAccount, setCurrentAccount] = useState("");
    const [mintResult, setMintResult] = useState(null);
    const checkIfWalletIsConnected = async () => {
      const { ethereum } = window;

      if (!ethereum) {
          console.log("Make sure you have metamask!");
          return;
      } else {
          console.log("We have the ethereum object", ethereum);
      }

      const accounts = await ethereum.request({ method: 'eth_accounts' });

      if (accounts.length !== 0) {
          const account = accounts[0];
          console.log("Found an authorized account:", account);
					setCurrentAccount(account)
          
          // Setup listener! This is for the case where a user comes to our site
          // and ALREADY had their wallet connected + authorized.
          setupEventListener()
      } else {
          console.log("No authorized account found")
      }
  }

  const connectWallet = async () => {
    try {
      const { ethereum } = window;

      if (!ethereum) {
        alert("Get MetaMask!");
        return;
      }

      const accounts = await ethereum.request({ method: "eth_requestAccounts" });

      console.log("Connected", accounts[0]);
      setCurrentAccount(accounts[0]);

      // Setup listener! This is for the case where a user comes to our site
      // and connected their wallet for the first time.
      setupEventListener() 
    } catch (error) {
      console.log(error)
    }
  }

  // Setup our listener.
  const setupEventListener = async () => {
    // Most of this looks the same as our function askContractToMintNft
    try {
      const { ethereum } = window;

      if (ethereum) {
        // Same stuff again
        const provider = new ethers.providers.Web3Provider(ethereum);
        const signer = provider.getSigner();
        const connectedContract = new ethers.Contract(CONTRACT_ADDRESS, myEpicNft.abi, signer);

        // THIS IS THE MAGIC SAUCE.
        // This will essentially "capture" our event when our contract throws it.
        // If you're familiar with webhooks, it's very similar to that!
        connectedContract.on("NewEpicNFTMinted", (from, tokenId) => {
          console.log(from, tokenId.toNumber());
          const url = 'https://testnets.opensea.io/assets';
          setMintResult(`${url}/${CONTRACT_ADDRESS}/${tokenId}`);
        });

        console.log("Setup event listener!")

      } else {
        console.log("Ethereum object doesn't exist!");
      }
    } catch (error) {
      console.log(error)
    }
  }

  const askContractToMintNft = async () => {
    try {
      setMinting(true);
      const { ethereum } = window;

      if (ethereum) {
        const provider = new ethers.providers.Web3Provider(ethereum);
        const signer = provider.getSigner();
        const connectedContract = new ethers.Contract(CONTRACT_ADDRESS, myEpicNft.abi, signer);

        console.log("Going to pop wallet now to pay gas...")
        let nftTxn = await connectedContract.makeAnEpicNFT();

        console.log("Mining...please wait.")
        await nftTxn.wait();
        console.log(nftTxn);
        console.log(`Mined, see transaction: https://rinkeby.etherscan.io/tx/${nftTxn.hash}`);

      } else {
        console.log("Ethereum object doesn't exist!");
      }
    } catch (error) {
      console.log(error)
    } finally {
      setMinting(false);
    }
  }


  useEffect(() => {
    checkIfWalletIsConnected();
  }, [])

  const renderNotConnectedContainer = () => (
    <button onClick={connectWallet} className="connect-wallet-button">
      CONNECT TO WALLET
    </button>
  );

  const handleGoBack = () => {
    setMintResult(null);
    setMinting(false);
  }

  const gotoOpensea = () => {
    window.location.href = mintResult;
  }

  const renderMintUI = () => {
    if (mintResult) {
      return (
        <>
          <div className="opensea-btn" onClick={gotoOpensea}>VISIT OPENSEA</div>
          <div className="back-btn" onClick={handleGoBack}>Mint another!</div>
        </>
      )
    }
    else if (minting) {
      return <div className="spinner"></div>;
    } else {
     return <div className="mint-button" onClick={askContractToMintNft}>MINT YOUR NFT</div>;
    }
  }
  return (
    <div className="container">
      <div className="paper">
        <di className="heading">Sayam Qazi's NFTs</di>
        {currentAccount === "" ? renderNotConnectedContainer() : renderMintUI()}
        <div className="disclaimer">disclaimer: hobbyist-project</div>
      </div>
    </div>
  )
  return (
    <div className="App">
      <div className="container">
        <div className="header-container">
          <p className="header gradient-text">My NFT Collection</p>
          <p className="sub-text">
            Each unique. Each beautiful. Discover your NFT today.
          </p>
          
        </div>
        <div className="footer-container">
          <img alt="Twitter Logo" className="twitter-logo" src={twitterLogo} />
          <a
            className="footer-text"
            href={TWITTER_LINK}
            target="_blank"
            rel="noreferrer"
          >{`built on @${TWITTER_HANDLE}`}</a>
        </div>
      </div>
    </div>
  );
};

export default App;

// nft-game/svelte-app/src/App.svelte
<script>
	import { onMount } from "svelte";
	import BattleArena from "./BattleArena.svelte";
	import CharacterSelect from "./CharacterSelect.svelte";
	import MyEpicGame from "./MyEpicGame.json";
	import { CONTRACT_ADDRESS, transformCharacterData } from "./constants";
	import { ethers } from "ethers";
	let currentAccount;
	let characterNFT;

	const checkIfWalletIsConnected = async () => {
		try {
			const { ethereum } = window;
			if (!ethereum) {
				return console.log("Make sure you have MetaMask!");
			} else {
				console.log("We have the ethereum object", ethereum);
				const accounts = await ethereum.request({ method: "eth_accounts" });
				if (accounts.length !== 0) {
					const account = accounts[0];
					console.log("Found an authorized account:", account);
					currentAccount = account;
				} else {
					console.log("No authorized account found");
				}
			}
		} catch (error) {
			console.log(error);
		}
	};

	/*
	 * Implement your connectWallet method here
	 */
	const connectWalletAction = async () => {
		try {
			const { ethereum } = window;
			if (!ethereum) return alert("Get MetaMask!");
			const accounts = await ethereum.request({
				method: "eth_requestAccounts",
			});
			console.log("Connected", accounts[0]);
			currentAccount = accounts[0];
		} catch (error) {
			console.log(error);
		}
	};

	onMount(() => {
		checkIfWalletIsConnected();
	});

	$: currentAccount, fetchMetadata();

	const fetchMetadata = async () => {
		if (!currentAccount) return;
		console.log("Checking for Character NFT on address:", currentAccount);
		const provider = new ethers.providers.Web3Provider(window.ethereum);
		const signer = provider.getSigner();
		const gameContract = new ethers.Contract(
			CONTRACT_ADDRESS,
			MyEpicGame.abi,
			signer
		);
		const txn = await gameContract.checkIfUserHasNFT();
		if (txn.name) {
			console.log("User has character NFT");
			characterNFT = transformCharacterData(txn);
			console.log(characterNFT)
		} else {
			console.log("No character NFT found");
		}
	};

	const handleCharacterNFT = (nft) => {
		characterNFT = nft;
	}
</script>

<div class="app">
	<div class="container">
		<div class="header-container">
			<p class="header gradient-text">😈 Issekai Demon Slayer 😈</p>
			<p class="sub-text">Team up to protect the realm!</p>
		</div>
		<div class="content-container">
			{#if !currentAccount}
				<div class="connect-wallet-container" on:click={connectWalletAction}>
					Connect Wallet
				</div>
			{:else if currentAccount && !characterNFT}
				<CharacterSelect setCharacterNFT={handleCharacterNFT} />
			{:else}
				<BattleArena characterNFT={characterNFT} />
			{/if}
		</div>
		<div class="footer-container">
			<a
				class="footer-text"
				href="https://twitter.com/sayamqazi"
				target="_blank"
				rel="noreferrer">built by @sayamqazi</a
			>
		</div>
	</div>
</div>

<style>
	.app {
		position: fixed;
		inset: 0;
		background: linear-gradient(#28313b, #485461);
		text-align: center;
	}

	.container {
		height: 100%;
		background-color: #0d1116;
		display: flex;
		flex-direction: column;
		justify-content: space-between;
	}

	.header-container {
		padding-top: 30px;
	}

	.header {
		margin: 0;
		font-size: 50px;
		font-weight: bold;
		color: white;
	}

	.sub-text {
		font-size: 25px;
		color: white;
	}

	.content-container {
		background-color: rgba(255, 255, 255, 0.05);
	}
	.connect-wallet-container {
		color: black;
		background-color: white;
		padding: 10px 15px;
		margin: 30px auto;
		border-radius: 5px;
		max-width: 220px;
		font-weight: bold;
		cursor: pointer;
	}

	/* 
	.mint-button {
		background: -webkit-linear-gradient(left, #a200d6, #ff6fdf);
		background-size: 200% 200%;
		animation: gradient-animation 4s ease infinite;
		margin-right: 15px;
	}

	.opensea-button {
		background-color: rgb(32, 129, 226);
	}

	.mint-count {
		color: white;
		font-size: 18px;
		font-weight: bold;
	} */

	.footer-container {
		display: flex;
		justify-content: center;
		align-items: center;
		padding-bottom: 30px;
	}

	.footer-text {
		color: white;
		font-size: 16px;
		font-weight: bold;
	}

	/* KeyFrames */
	@-webkit-keyframes gradient-animation {
		0% {
			background-position: 0% 50%;
		}
		50% {
			background-position: 100% 50%;
		}
		100% {
			background-position: 0% 50%;
		}
	}
	@-moz-keyframes gradient-animation {
		0% {
			background-position: 0% 50%;
		}
		50% {
			background-position: 100% 50%;
		}
		100% {
			background-position: 0% 50%;
		}
	}
	@keyframes gradient-animation {
		0% {
			background-position: 0% 50%;
		}
		50% {
			background-position: 100% 50%;
		}
		100% {
			background-position: 0% 50%;
		}
	}
</style>
